send_followup_email:
  description: >
    Soạn thảo email theo dõi cá nhân hóa cho các ứng viên đã nộp đơn vào một công việc cụ thể.

    Bạn sẽ sử dụng tên, tiểu sử của ứng viên và liệu công ty có muốn tiếp tục với họ hay không để tạo ra email. 
    Nếu ứng viên được tiếp tục, hãy hỏi họ về thời gian có thể tham gia cuộc gọi Zoom trong những ngày tới. 
    Nếu không, hãy gửi một email từ chối lịch sự.

    THÔNG TIN ỨNG VIÊN
    -----------------
    ID Ứng Viên: {candidate_id}
    Tên: {name}
    Tiểu sử:
    {bio}

    TIẾP TỤC VỚI ỨNG VIÊN: {proceed_with_candidate}

    HƯỚNG DẪN THÊM
    -----------------------
    - Nếu chúng ta tiếp tục, hãy hỏi về thời gian có thể tham gia cuộc gọi Zoom trong vài ngày tới.
    - Nếu chúng ta không tiếp tục, hãy gửi một email từ chối lịch sự, ghi nhận nỗ lực của họ trong việc nộp đơn và cảm ơn thời gian của họ.
    - Hãy đưa đường dẫn của công ty cho ứng viên tham khảm: https://mbw.vn/

  expected_output: >
    Một email cá nhân hóa dựa trên thông tin của ứng viên. Nó nên chuyên nghiệp và tôn trọng, 
    hoặc mời họ tham gia cuộc gọi Zoom hoặc cho họ biết rằng chúng ta đang theo đuổi các ứng viên khác.
    Đầu ra là tiếng việt.
  agent: email_followup_agent
